# Generated by Django 5.0.2 on 2024-02-21 11:07

import django.core.validators
import django.db.models.deletion
import habit_tracker.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=255)),
                ('time', models.TimeField()),
                ('action', models.CharField(max_length=255)),
                ('pleasant', models.BooleanField(default=False)),
                ('frequency', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), habit_tracker.validators.validate_frequency])),
                ('reward', models.CharField(blank=True, max_length=255, null=True, validators=[habit_tracker.validators.validate_reward_and_related_habit])),
                ('duration', models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(1), habit_tracker.validators.validate_duration])),
                ('is_public', models.BooleanField(default=False)),
                ('related_habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='habit_tracker.habit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
